drop table carro if exists cascade constraints;
create table carro (
  id bigint generated by default as identity,
  descricao varchar(255),
  latitude varchar(255),
  longitude varchar(255),
  nome varchar(255),
  tipo varchar(255),
  url_foto varchar(255),
  url_video varchar(255),
  primary key (id)
);

drop table user if exists cascade constraints;
create table user (
  id bigint not null auto_increment,
  email varchar(255),
  login varchar(255),
  nome varchar(255),
  senha varchar(255),
  primary key (id)
);

drop table role if exists cascade constraints;
create table role (
  id bigint not null auto_increment,
  nome varchar(255),
  primary key (id)
);

drop table user_roles if exists cascade constraints;
create table user_roles (
  user_id bigint not null,
  role_id bigint not null
);

alter table user_roles 
  add constraint FK55itppkw3i07do3h7qoclqd4k 
  foreign key (user_id) 
  references user (id);


alter table user_roles 
  add constraint FKrhfovtciq1l558cw6udg0h0d3 
  foreign key (role_id) 
  references role (id);
